-- CreateTable
CREATE TABLE "CourtCase" (
    "entered_date_time" TIMESTAMP(3) NOT NULL,
    "entered_by" TEXT NOT NULL,
    "guid" TEXT NOT NULL,
    "court_case_number" TEXT NOT NULL,
    "defendant_name" TEXT NOT NULL,
    "defendant_dob" TIMESTAMP(3) NOT NULL,
    "lea_number" TEXT NOT NULL,
    "agent" TEXT NOT NULL,
    "agency" TEXT NOT NULL,
    "incident_date" TIMESTAMP(3) NOT NULL,
    "arrest_date" TIMESTAMP(3) NOT NULL,
    "incident_location" TEXT NOT NULL,
    "charges" TEXT[],
    "felony_warrant" BOOLEAN NOT NULL,
    "family_violence" BOOLEAN NOT NULL,
    "assigned_opener" TEXT,
    "codefendant" TEXT,
    "division" TEXT,
    "justice_reform_attorney" TEXT,
    "tier" INTEGER,
    "tier_reason" TEXT,
    "tier_reason_other" TEXT,
    "pdm" BOOLEAN,
    "pdm_reason" TEXT,
    "no_pdm_reason" TEXT,
    "pdm_attorney" TEXT,
    "four_zero_three" BOOLEAN,
    "four_zero_three_case_numbers" TEXT,
    "district_court_number" TEXT,
    "da_number" TEXT,
    "four_zero_three_attorney" TEXT,
    "course_of_action" TEXT,
    "diversion" TEXT,
    "diversion_reason" TEXT,
    "federal_charges" TEXT,
    "notes" TEXT,
    "pv_hold" BOOLEAN,
    "firearm" BOOLEAN,
    "reviewed_by" TEXT,
    "weekend" BOOLEAN,

    CONSTRAINT "CourtCase_pkey" PRIMARY KEY ("guid")
);
